# Generated by Django 5.2.8 on 2025-12-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereco')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
    ]
